Update msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -1,4 +1,4 @@
-name: MSBuild
+name: MSBuild Workflow
 
 on:
   push:
@@ -14,24 +14,32 @@ permissions:
   contents: read
 
 jobs:
- build:
+  build:
     runs-on: windows-latest
     strategy:
       matrix:
         BUILD_CONFIGURATION: [Release, Debug]
         BUILD_PLATFORM: [x64, x86]
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Add MSBuild to PATH
-      uses: microsoft/setup-msbuild@v1.1.3
+      - name: Add MSBuild to PATH
+        uses: microsoft/setup-msbuild@v1.1.3
 
-    - name: Restore NuGet packages
-      working-directory: ${{env.GITHUB_WORKSPACE}}
-      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
+      - name: Restore NuGet packages
+        working-directory: ${{env.GITHUB_WORKSPACE}}
+        run: |
+          nuget restore ${{env.SOLUTION_FILE_PATH}} -Verbosity detailed
+          if ($LastExitCode -ne 0) {
+            Write-Error "NuGet package restore failed."
+            exit $LastExitCode
+          }
 
-    - name: Build
-      working-directory: ${{env.GITHUB_WORKSPACE}}
-      # Add additional options to the MSBuild command line here (like platform or verbosity level).
-      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
-      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
+      - name: Build
+        working-directory: ${{env.GITHUB_WORKSPACE}}
+        run: |
+          msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
+          if ($LastExitCode -ne 0) {
+            Write-Error "MSBuild failed."
+            exit $LastExitCode
+          }
